my_app/urls.py
from django.conf.urls import url
from .views import index, saveTaskInfo, tasksearch, taskfilter, edittask

urlpatterns = [
	url(r'^saveTaskInfo/', saveTaskInfo.as_view(),name='saveTaskInfo'),
	url(r'^edittask/(?P<id>\d+)/$', edittask.as_view(),name='edittask'),
	url(r'^tasksearch/', tasksearch, name='tasksearch'),
	url(r'^taskfilter/', taskfilter, name='taskfilter'),

    url(r'^$', index.as_view(),name='index'),
]

to_do_list/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^', include('my_app.urls',namespace='app')),
]

my_app/models.py
from django.db import models

class task(models.Model):

    Title    	= models.CharField(max_length=120, null=True)
    Description = models.CharField(max_length=4800, null=True)
    Due_Date  	= models.DateField(auto_now=False, auto_now_add=False, null=True)

    def __str__(self):
        return self.Title

class subtask(models.Model):

    Title    	= models.CharField(max_length=120, null=True)
    Description = models.CharField(max_length=4800, null=True)
    Due_Date  	= models.DateField(auto_now=False, auto_now_add=False, null=True)
    task 		= models.ForeignKey(task, on_delete=models.CASCADE, to_field='id', null=True)

    def __str__(self):
        return self.Title

my_app/forms.py
from django import forms 
from .models import task

class TaskinformForm(forms.ModelForm):
	class Meta:
		model=task
		
		fields = [
		'Title',
		'Description',
		'Due_Date',
		]

		labels = {
		'Title':'Title',
		'Description':'Description',
		'Due_Date':'Due_Date',
		}

		widgets = {
		'Title'			:forms.TextInput(attrs={'name':'eventname','class':'form-control','placeholder':'Title',}),
		'Description'	:forms.TextInput(attrs={'name':'eventdays','class':'form-control','placeholder':'Description'}),
		'Due_Date'		:forms.DateInput(attrs={'type':'date','name':'eventdate','class':'form-control','placeholder':'Due_Date'}),
		}

my_app/views.py
from django.shortcuts import render, redirect
from django.views import View
from .forms import TaskinformForm
from .models import task

import datetime

from django.db.models import Q
from django.contrib import messages

import pdb

class index(View):
	def get(self, request, *args, **Kwargs):

		form = TaskinformForm()
		taskinfo = task.objects.order_by('Due_Date').all()
		today  = datetime.date.today()
		
		context = {
			'form':form,
			'task':taskinfo,
			'todayDate':today
			}
		return render(request,'my_app/index.html',context)

class saveTaskInfo(View):
	def post(self, request, *args, **Kwargs):

		form=TaskinformForm(self.request.POST)
		
		if form.is_valid():
			form.save()

		return redirect( 'app:index' )

def tasksearch(request):
	if request.method == 'POST':
		srch  = request.POST['search']

		if srch:
			match = task.objects.filter(Q(Title__icontains = srch))

			form = TaskinformForm()
			taskinfo = task.objects.order_by('Due_Date').all()
			today  = datetime.date.today()

			if match:
				context = {
				'srch':match,
				'form':form,
				'task':taskinfo,
				'todayDate' :today
				}
				return render(request,'my_app/index.html',context)

			else:
				messages.error(request,'No Result Found.')
		       
		else:
			return render(request,'my_app/index.html')

	return render(request,'my_app/index.html')

def taskfilter(request):
	datefilter = request.POST.get('filter')
	today  = datetime.date.today()

	if datefilter == 'today':
		taskinfo = task.objects.filter(Due_Date__icontains=today).order_by('Due_Date')
	elif datefilter == 'thisweek':
		startdate = datetime.date.today()
		enddate = startdate + datetime.timedelta(days=6)
		taskinfo = task.objects.filter(Due_Date__range=[startdate, enddate]).order_by('Due_Date')
	elif datefilter == 'nextweek':
		startdate = datetime.date.today() + datetime.timedelta(days=6)
		enddate = startdate + datetime.timedelta(days=6)
		taskinfo = task.objects.filter(Due_Date__range=[startdate, enddate]).order_by('Due_Date')
	else:
		None
	
	form = TaskinformForm()
	
	context = {
		'form':form,
		'task':taskinfo,
		'todayDate':today
		}
	return render(request,'my_app/index.html',context)

class edittask(View):
	def get(self, request, *args, **Kwargs):
		taskid = request.session['taskid'] = Kwargs['id']

		if (task.objects.filter(id = taskid).exists()):
			form = TaskinformForm(instance = task.objects.get(id = taskid))
			return render(request,'my_app/edit_task.html',{'form' : form})

		else:
			form = TaskinformForm()
			return render(request,'my_app/edit_task.html',{'form' : form})
	
		return redirect( 'app:index' )

	def post(self, request, *args, **Kwargs):
		taskid = request.session['taskid']

		if (task.objects.filter(id = taskid).exists()):
			if self.request.method == 'POST':
				form=TaskinformForm(self.request.POST,instance = task.objects.get(id = taskid))

				if form.is_valid():
					form.save()
					return redirect( 'app:index' )
            
		else:
			form = TaskinformForm(self.request.POST)
			if self.request.method == 'POST':
				if form.is_valid():
					fform = form.save()

		return redirect( 'app:index' )

def addsubtask(request):
	
	return redirect( 'app:index' )

my_app/templates/my_app/edit_task.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>To-do-List | Index</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
	<form action="{% url 'app:saveTaskInfo' %}" method="POST">
		{% csrf_token %}
		{{ form }}
		<br>
		<button type="submit" class="btn btn-primary">Save</button>
		<a href="{% url 'app:index' %}"><button type="button" class="btn btn-primary">Back</button></a>
	</form>

	{{ form.id }}
<script
src="https://code.jquery.com/jquery-3.3.1.min.js"
integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

my_app/templates/my_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>To-do-List | Index</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
  <center>
    <h1>Welcome to To - Do - List Page</h1>

    <br>
    <br>
    <br>

    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
      Add Task
    </button>
    <a href="{%url 'app:index'%}"><input type="button" class="btn btn-primary" value="Reset"></a>

    <br>
    <br>

    <form action="{%url 'app:tasksearch'%}" method="POST">
      {% csrf_token %}
      <input id="search_text" type="text" name="search" placeholder="Enter Title of Task to Search" style="margin-right: 0px; padding-right: 50px" />
      <input class="btn btn-lng btn-danger" id="" type="Submit" value="Search" style="margin-right: 20px;"/>
    </form>

    <br>

    <form action="{%url 'app:taskfilter'%}" method="POST">
      {% csrf_token %}
     <div class="form-group">
      <label for="sel1">Select Date Range :    </label>
      <select class="form-group" name="filter">
        <option value="today">Today</option>
        <option value="thisweek">This Week</option>
        <option value="nextweek">Next Week</option>
        <option value="overdue">Over Due</option>
      </select>
    </div> 
    <input class="btn btn-lng btn-danger" id="" type="Submit" value="Filter"/>
  </form>

  {% if srch %}
  <table class="table">
    <thead>
      <tr>
        <th style="text-align: center;">Title</th>
        <th style="text-align: center;">Description</th>
        <th style="text-align: center;">Due Date</th>
        <th style="text-align: center;">Status</th>
      </tr>
    </thead>
    <tbody>
      {% for s in srch %}
      <tr>
        <td style="text-align: center;">{{ s.Title }}</td>
        <td style="text-align: center;">{{ s.Description }}</td>
        <td style="text-align: center;">{{ s.Due_Date }}</td>
        {% if t.Due_Date > todayDate %}
        <td style="text-align: center; color:green;">Pending</td>
        {% else %}
        <td style="text-align: center; color:red;">Completed</td>
      </tr>
      {% endif %}{% endfor %}
    </tbody>
  </table>
  {% endif %}
</center>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Form to Add Task</h4>
      </div>
      <form method="POST" action="{% url 'app:saveTaskInfo' %}">
        {% csrf_token %}

        <div class="modal-body">
          {{ form }}

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Save</button>
        </div>
      </form>
    </div>
  </div>
</div>

<br>
<br>
<br>

<center>
  <table class="table">
    <thead>
      <tr>
        <th style="text-align: center;">Title</th>
        <th style="text-align: center;">Description</th>
        <th style="text-align: center;">Due Date</th>
        <th style="text-align: center;">Status</th>
        <th style="text-align: center;"></th>
        <th style="text-align: center;"></th>
      </tr>
    </thead>
    <tbody>
      {% for t in task %}
      <tr>
        <td style="text-align: center;">{{ t.Title }}</td>
        <td style="text-align: center;">{{ t.Description }}</td>
        <td style="text-align: center;">{{ t.Due_Date }}</td>
        {% if t.Due_Date > todayDate %}
        <td style="text-align: center; color:green;">Pending</td>
        {% else %}
        <td style="text-align: center; color:red;">Completed</td>
        {% endif %}
        <td style="text-align: center;">
          <a href="{% url 'app:edittask' id=t.id %}"><input type="button" name="" value="Edit"></a>
        </td>
        <td style="text-align: center;">
          <input type="button" name="" value="Add Sub Task">
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</center>

<script
src="https://code.jquery.com/jquery-3.3.1.min.js"
integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<script type="text/javascript">
  
</script>

</body>
</html>